### PR TITLE
User-as-a-case

### PR DESCRIPTION
**Pull request by kaapstorm**
This feature allows user data and activity to be tracked in a case.

Case properties are available using the prefix "user:", e.g. "user:dob" or "user:last_activity". The user case generally behaves like any other case.

### CODE REVIEW

File: corehq/apps/app_manager/tests/test_suite.py [hunk 1]
```diff
@@ -323,6 +323,37 @@ def test_tiered_select_with_advanced_module_as_parent(self):
 
         self.assertXmlPartialEqual(self.get_xml('advanced_module_parent'), app.create_suite(), "./entry[1]")
 
+# Just use AdvancedModule
+
+
+    def test_usercase_id_added_update(self):
```
Comment (dimagimon) [inline corehq/apps/app_manager/tests/test_suite.py]: E303 too many blank lines (2)

File: corehq/apps/app_manager/xform.py [hunk 2]
```diff
@@ -970,6 +980,93 @@ def already_has_meta(self):
...
+
+    def add_usercase(self, form):
+        from corehq.apps.app_manager.util import split_path
+
+        usercase_path = 'usercase/'
+        actions = form.active_actions()
+        usercase_bound = False
+
+        if 'update_case' in actions and hasattr(actions['update_case'], 'update'):
+            usercase_updates = {k[5:]: v for k, v in actions['update_case'].update.items() if k.startswith('user:')}
```
Comment (dimagimon) [inline corehq/apps/app_manager/xform.py]: E501 line too long (116 > 115 characters)

File: corehq/apps/app_manager/xform.py [hunk 3]
```diff
@@ -970,6 +980,93 @@ def already_has_meta(self):
...
+                    usercase_bound = True
+                usercase_block = _make_elem('{x}usercase')
+                case_block = CaseBlock(self, usercase_path)
+                case_block.add_update_block(usercase_updates)
+                usercase_block.append(case_block.elem)
+                self.data_node.append(usercase_block)
+
+        if 'case_preload' in actions:
+            self.add_casedb()
+            usercase_preloads = {k: v[5:] for k, v in actions['case_preload'].preload.items() if v.startswith('user:')}
```
Comment (dimagimon) [inline corehq/apps/app_manager/xform.py]: E501 line too long (119 > 115 characters)

File: corehq/apps/app_manager/xpath.py [hunk 4]
```diff
@@ -12,8 +12,8 @@ def dot_interpolate(string, replacement):
     return re.sub(pattern, repl, string)
 
 
-def session_var(var, subref=None):
-    return XPath(u"instance('commcaresession')/session/{0}data/{1}".format(subref + '/' if subref else '', var))
+def session_var(var, subref=None, data=u'data'):
+    return XPath(u"instance('commcaresession')/session/{0}{1}/{2}".format(subref + '/' if subref else '', data, var))
```
Comment (dimagimon) [inline corehq/apps/app_manager/xpath.py]: E501 line too long (117 > 115 characters)

File: corehq/apps/app_manager/tests/test_suite.py [hunk 5]
```diff
@@ -323,6 +323,37 @@ def test_tiered_select_with_advanced_module_as_parent(self):
 
         self.assertXmlPartialEqual(self.get_xml('advanced_module_parent'), app.create_suite(), "./entry[1]")
 
+# Just use AdvancedModule
```
Comment (kaapstorm) [inline corehq/apps/app_manager/tests/test_suite.py]: Tests for updating from and preloading into advanced forms pending.

File: corehq/apps/app_manager/suite_xml.py [hunk 6]
```diff
@@ -1581,6 +1604,14 @@ def get_datum_session_var(action, action_index):
 
             return case_session_var
 
+        def uses_usercase(form):
+            for action in form.actions.load_update_cases:
+                if action.preload:
```
Comment (benrudolph) [inline corehq/apps/app_manager/suite_xml.py]: could this be simplified to 
```
if action.preload or action.case_properties
  return any(k.startswith('user:') for k in action.preload.keys())
```

File: corehq/apps/app_manager/tests/test_suite.py [hunk 7]
```diff
@@ -393,7 +424,7 @@ def test_case_list_registration_form_advanced(self):
         case_module.case_type = 'dugong'
         update_form = app.new_form(1, 'Update Case', lang='en')
         update_form.unique_id = 'update_case_form'
-        update_form.actions.load_update_cases.append(LoadUpdateAction(
+        update_form.actions.load_update_cases.append(LoadUpdateAction(  # <-- e.g.
```
Comment (benrudolph) [inline corehq/apps/app_manager/tests/test_suite.py]: probably don't need this anymore

File: corehq/apps/app_manager/views.py [hunk 8]
```diff
@@ -867,33 +912,6 @@ def case_list_form_options(case_type):
         }
     elif isinstance(module, AdvancedModule):
         case_type = module.case_type
-        def get_details():
```
Comment (benrudolph) [inline corehq/apps/app_manager/views.py]: +1 for pulling this out

File: corehq/apps/app_manager/tests/test_suite.py (hunk 7 above)
Comment (kaapstorm) [inline corehq/apps/app_manager/tests/test_suite.py]: True. Currently working on two tests for advanced forms and that comment is gone. (If I'd noticed that comment earlier, I wouldn't have committed it.)

File: corehq/apps/app_manager/suite_xml.py (hunk 6 above)
Comment (kaapstorm) [inline corehq/apps/app_manager/suite_xml.py]: :+1:

File: corehq/apps/app_manager/xform.py (hunk 2 above)
Comment (benrudolph) [inline corehq/apps/app_manager/xform.py]: I'm assuming the `5:` is cutting off the 'user:' prefix. Small, but might be nice if we had a constant for `"user:"`. Then we could reduce spelling errors ever and in this scenario we could do `k[len(USERCASE_PREFIX):]` and it'd be clear that we're chopping off the user prefix

File: corehq/apps/app_manager/xform.py [hunk 9]
```diff
@@ -970,6 +980,93 @@ def already_has_meta(self):
...
+                    }.get(property_, property_)
+
+                    id_xpath = get_case_parent_id_xpath(parent_path, case_id_xpath=SESSION_USERCASE_ID)
+                    self.add_setvalue(
+                        ref=nodeset,
+                        value=id_xpath.case().property(property_xpath),
+                    )
+
+            if action.case_properties:
+                usercase_updates = {k[5:]: v for k, v in action.case_properties.items() if k.startswith('user:')}
```
Comment (benrudolph) [inline corehq/apps/app_manager/xform.py]: this is coming up a lot, maybe a mall utility function could be useful

**Comment by benrudolph** [comment]
cool lookin nice, excited for this

File: corehq/apps/app_manager/suite_xml.py [hunk 10]
```diff
@@ -1581,6 +1605,12 @@ def get_datum_session_var(action, action_index):
 
             return case_session_var
 
+        def uses_usercase(form):
+            for action in form.actions.load_update_cases:
+                if action.preload or action.case_properties:
+                    return any_usercase_items(action.preload.keys())
```
Comment (snopoke) [inline corehq/apps/app_manager/suite_xml.py]: don't you also need to check `action.case_properties`?

File: corehq/apps/app_manager/suite_xml.py [hunk 11]
```diff
@@ -1407,11 +1416,26 @@ def case_sharing_requires_assertion(form):
                         return True
             return False
 
+        def updates_usercase(form):
+            actions = form.active_actions()
+            if 'update_case' in actions and hasattr(actions['update_case'], 'update'):
+                return any_usercase_items(actions['update_case'].update.keys())
+            return False
+
+        def preloads_usercase(form):
```
Comment (snopoke) [inline corehq/apps/app_manager/suite_xml.py]: Seems like you could combine these two functions since they only ever get used together

File: corehq/apps/app_manager/util.py [hunk 12]
```diff
@@ -146,11 +149,24 @@ def get_properties(self, case_type, already_visited=(),
...
+
+        # .. note:: if the user case type has a parent case type, its
+        #           properties will be returned as `user:parent/property`
+        #
+        # .. note:: if this case type is not the user case type, but it has a
+        #           parent case type which is the user case type, then the
+        #           parent case type's properties will be returned as
+        #           `parent/user:property`. That's probably unlikely, and a
+        #           good thing that it is, because that looks like a mess, and
+        #           will likely cause problems.
```
Comment (snopoke) [inline corehq/apps/app_manager/util.py]: This may not be as unlikely as you think. I can quite easily foresee people creating child cases of the user case e.g. one case per exam.

I think its fine not to handle that now but is likely something we'll need to figure out.

File: corehq/apps/app_manager/xform.py [hunk 13]
```diff
@@ -970,6 +981,93 @@ def already_has_meta(self):
...
+        )
+
+    def add_usercase(self, form):
+        from corehq.apps.app_manager.util import split_path
+
+        usercase_path = 'usercase/'
+        actions = form.active_actions()
+        usercase_bound = False
+
+        if 'update_case' in actions and hasattr(actions['update_case'], 'update'):
```
Comment (snopoke) [inline corehq/apps/app_manager/xform.py]: Why is the `hasattr` check needed here?

File: corehq/apps/app_manager/xform.py [hunk 14]
```diff
@@ -970,6 +981,93 @@ def already_has_meta(self):
...
+                case_block = CaseBlock(self, usercase_path)
+                case_block.add_update_block(usercase_updates)
+                usercase_block.append(case_block.elem)
+                self.data_node.append(usercase_block)
+
+        if 'case_preload' in actions:
+            self.add_casedb()
+            usercase_preloads = get_usercase_values(actions['case_preload'].preload.items())
+            if usercase_preloads and not usercase_bound:
+                self._add_usercase_bind(usercase_path)
```
Comment (snopoke) [inline corehq/apps/app_manager/xform.py]: You don't need to add a bind for preloading, only for updating.

File: corehq/apps/app_manager/xform.py [hunk 15]
```diff
@@ -970,6 +981,93 @@ def already_has_meta(self):
...
+                usercase_bound = True
+            for nodeset, property_ in usercase_preloads.items():
+                parent_path, property_ = split_path(property_)
```
Comment (snopoke) [inline corehq/apps/app_manager/xform.py]: I don't think this is necessary since the user case will never have a parent.

File: corehq/apps/app_manager/xform.py [hunk 16]
```diff
@@ -970,6 +981,93 @@ def already_has_meta(self):
...
+                    'owner_id': '@owner_id'
+                }.get(property_, property_)
+
+                id_xpath = get_case_parent_id_xpath(parent_path, case_id_xpath=SESSION_USERCASE_ID)
+                self.add_setvalue(
+                    ref=nodeset,
+                    value=id_xpath.case().property(property_xpath),
+                )
+
+    def add_usercase_advanced(self, form):
```
Comment (snopoke) [inline corehq/apps/app_manager/xform.py]: I'm thinking we should handle the advanced forms differently and rather than mixing in the user case properties in other actions we should just have a separate action with only user case properties. That way we wouldn't have to add any new code to suite_xml.py or xform.py to for advanced forms / modules.

Can chat more about this offline.

File: corehq/apps/app_manager/xpath.py [hunk 17]
```diff
@@ -112,6 +113,10 @@ def case(self):
         return CaseXPath(u"instance('casedb')/casedb/case[%s='%s']" % (self.selector, self))
 
 
+class UserCaseXPath(CaseSelectionXPath):
+    selector = 'user_id'
```
Comment (snopoke) [inline corehq/apps/app_manager/xpath.py]: I think this should be more specific:
```
instance('casedb')/casedb/case[@case_type='user_case'][hq_user_id={user_id in session}]
```
See also: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/callcenter/utils.py#L73-73

File: corehq/apps/callcenter/utils.py [hunk 18]
```diff
@@ -32,6 +32,7 @@ def valid_element_name(name):
     fields.update({
         'name': commcare_user.name or commcare_user.raw_username,
         'username': commcare_user.raw_username,
+        'user_id': commcare_user.get_id,
```
Comment (snopoke) [inline corehq/apps/callcenter/utils.py]: this already gets added: https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/callcenter/utils.py#L73-73

**Comment by snopoke** [comment]
bump

File: corehq/apps/app_manager/suite_xml.py [hunk 19]
```diff
@@ -18,14 +18,16 @@
     SuiteValidationError,
 )
 from corehq.apps.app_manager import id_strings
+from corehq.apps.app_manager.const import CAREPLAN_GOAL, CAREPLAN_TASK, SCHEDULE_LAST_VISIT, SCHEDULE_PHASE, \
```
Comment (dimagimon) [inline corehq/apps/app_manager/suite_xml.py]: F401 'CASE_ID' imported but unused

Comment (dimagimon) [inline corehq/apps/app_manager/suite_xml.py]: F401 'USERCASE_PREFIX' imported but unused

File: corehq/apps/app_manager/suite_xml.py [hunk 20]
```diff
@@ -1664,6 +1694,9 @@ def get_datum_session_var(action, action_index):
         if self.app.case_sharing and case_sharing_requires_assertion(form):
             self.add_case_sharing_assertion(e)
 
+        if uses_usercase(form):
```
Comment (dimagimon) [inline corehq/apps/app_manager/suite_xml.py]: F821 undefined name 'uses_usercase'

**Comment by dannyroberts** [comment]
:X:

**Comment by czue** [comment]
```
3.49s$ coverage run manage.py test --noinput --failfast --traceback --testrunner=$TEST_RUNNER
Traceback (most recent call last):
  File "manage.py", line 65, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/home/travis/virtualenv/local/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 25, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
ImproperlyConfigured: ImportError corehq.apps.userhack: cannot import name XForm
```

**Comment by snopoke** [comment]
That usually means the is a circular import reference somewhere.

**Comment by kaapstorm** [comment]
Yes. :-( And missing `uses_usercase` was accidentally deleted in a bad merge.

File: corehq/apps/cloudcare/views.py [hunk 21]
```diff
@@ -1,11 +1,14 @@
 import uuid
-from couchdbkit import ResourceConflict
+from corehq.apps.app_manager.const import USERCASE_ID
+from corehq.apps.hqcase.utils import get_case_by_domain_hq_user_id
+from couchdbkit import ResourceConflict, NoResultFound
```
Comment (dimagimon) [inline corehq/apps/cloudcare/views.py]: F401 'NoResultFound' imported but unused

File: corehq/apps/smsforms/app.py [hunk 22]
```diff
@@ -1,5 +1,8 @@
 import uuid
+from corehq.apps.app_manager.const import USERCASE_ID
 from corehq.apps.app_manager.suite_xml import SuiteGenerator
+from corehq.apps.hqcase.utils import get_case_by_domain_hq_user_id
+from couchdbkit import NoResultFound
```
Comment (dimagimon) [inline corehq/apps/smsforms/app.py]: F401 'NoResultFound' imported but unused

File: corehq/apps/app_manager/suite_xml.py [hunk 23]
```diff
@@ -21,14 +21,16 @@
 )
 from corehq.toggles import MODULE_FILTER
 from corehq.apps.app_manager import id_strings
+from corehq.apps.app_manager.const import CAREPLAN_GOAL, CAREPLAN_TASK, SCHEDULE_LAST_VISIT, SCHEDULE_PHASE, \
```
Comment (dimagimon) [inline corehq/apps/app_manager/suite_xml.py]: F401 'CASE_ID' imported but unused

File: corehq/apps/callcenter/utils.py [hunk 24]
```diff
@@ -3,87 +3,111 @@
...
+
+        def valid_element_name(name):
+            try:
+                ElementTree.fromstring('<{}/>'.format(name))
+                return True
+            except ElementTree.ParseError:
+                return False
+
+        # remove any keys that aren't valid XML element names
+        fields = {k: v for k, v in commcare_user.user_data.items() if valid_element_name(k)} if copy_user_data else {}
```
Comment (dimagimon) [inline corehq/apps/callcenter/utils.py]: E501 line too long (118 > 115 characters)

**Comment by kaapstorm** [comment]
Thanks for all the feedback, @snopoke, @gcapalbo. Updates pushed.

I've got some questions about CriticalSection. We only seem to use it in these places:
* corehq/apps/reminders/models.py
* corehq/apps/reminders/views.py
* corehq/apps/reminders/tasks.py
* corehq/apps/reminders/event_handlers.py
* corehq/apps/sms/verify.py
* corehq/apps/app_manager/util.py
* corehq/apps/kookoo/views.py
* submodules/dimagi-utils-src/dimagi/utils/multithreading.py
* submodules/dimagi-utils-src/dimagi/utils/couch/\_\_init\_\_.py

We don't seem to use it for syncing cases, even user cases for call center. How come? Is that potentially a bug in call center? 

I've added it in both places you suggested, @gcapalbo, and I've committed them separately in case I need to revert.

[The lock in enable_usercase][1] will return quickly because creating the usercases happens asynchronously, and if a process is waiting for the lock, when it's released they'll find that usercase is already enabled on the domain and that there is nothing to do. So that seems right. I think this will only get called because of a change made in the app builder. Or am I missing another scenario? What are the chances that two users will be modifying the same app simultaneously? Even though the chances are small, should we lock it on principle, or not bother?

Regarding [locking in sync_user_case][2], we're using a different key to the one we use in enable_usercase because we're locking on each usercase, instead of all usercases for a domain. What happens if an FM enables usercase at the same time that a user is saved? That user's case will be synced with two different locks. Is this something we need to consider? The chances seem really small. And if there is a race condition, what would break?


  [1]: https://github.com/dimagi/commcare-hq/commit/21d3b863f384d92359de00725cea5917061830a9
  [2]: https://github.com/dimagi/commcare-hq/commit/5496d31acbb2bc09be35e66b442796f0de940e14

**Comment by snopoke** [comment]
That all seems fine. I think the only scenario we should care about in the `sync_user_case` function is if two cases get created for the same user but the lock should prevent that.

File: corehq/apps/app_manager/views.py [hunk 25]
```diff
@@ -1060,6 +1066,7 @@ def qualified_form_name(form):
     })
 
     context['latest_commcare_version'] = get_commcare_versions(request.user)[-1]
+    context['usercase_enabled'] = Domain.get_by_name(domain).call_center_config.enabled
```
Comment (snopoke) [inline corehq/apps/app_manager/views.py]: Need to change this to use new domain property.

File: corehq/apps/callcenter/utils.py (hunk 24 above)
Comment (snopoke) [inline corehq/apps/callcenter/utils.py]: Still need to remove these from the user case (but keep them for the call center cases)

File: corehq/apps/cloudcare/views.py [hunk 26]
```diff
@@ -199,6 +202,9 @@ def form_context(request, domain, app_id, module_id, form_id):
     suite_gen = SuiteGenerator(app)
     datums = suite_gen.get_new_case_id_datums_meta(form)
     session_extras.update({datum['datum'].id: uuid.uuid4().hex for datum in datums})
+    usercase = get_case_by_domain_hq_user_id(domain, request.couch_user.get_id, include_docs=False)
+    if usercase:
+        session_extras[USERCASE_ID] = usercase['id']
```
Comment (snopoke) [inline corehq/apps/cloudcare/views.py]: Should only add this if required.

File: corehq/apps/domain/forms.py [hunk 27]
```diff
@@ -392,9 +393,10 @@ class DomainGlobalSettingsForm(forms.Form):
                     "of all cases created for call center users.")
     )
     call_center_case_type = CharField(
-        label=_("Call Center Case Type"),
         required=False,
-        help_text=_("Enter the case type to be used for FLWs in call center apps")
+        # Hide the case type, but keep the form field in order to preserve
+        # existing values on update.
+        widget=forms.HiddenInput()
```
Comment (snopoke) [inline corehq/apps/domain/forms.py]: Can undo this change.

File: corehq/apps/smsforms/app.py [hunk 28]
```diff
@@ -59,6 +61,10 @@ def start_session(domain, contact, app, module, form, case_id=None, yield_respon
         suite_gen = SuiteGenerator(app)
         datums = suite_gen.get_new_case_id_datums_meta(form)
         session_data.update({meta['datum'].id: uuid.uuid4().hex for meta in datums})
+        if contact.doc_type == 'CommCareUser':
+            usercase = get_case_by_domain_hq_user_id(domain, contact.get_id, include_docs=False)
+            if usercase:
+                session_data[USERCASE_ID] = usercase['id']
```
Comment (snopoke) [inline corehq/apps/smsforms/app.py]: again, only do this if necessary

File: corehq/apps/app_manager/suite_xml.py [hunk 29]
```diff
@@ -1490,6 +1496,28 @@ def get_auto_select_assertions(self, case_id_xpath, mode, locale_arguments=None)
...
+        def uses_usercase(form_):
+            actions = form_.active_actions()
+            if 'update_case' in actions and hasattr(actions['update_case'], 'update'):
+                return any_usercase_items(actions['update_case'].update.keys())
+            if 'case_preload' in actions:
+                return any_usercase_items(actions['case_preload'].preload.values())
+            return False
+
+        datums = []
+        if form.form_type == 'module_form' and uses_usercase(form) and self.is_usercase_enabled:
```
Comment (snopoke) [inline corehq/apps/app_manager/suite_xml.py]: if the form has 'user case' properties but `self.is_usercase_enabled` is false that seems like an error that should prevent the build.

File: corehq/apps/app_manager/suite_xml.py [hunk 30]
```diff
@@ -1490,6 +1496,28 @@ def get_auto_select_assertions(self, case_id_xpath, mode, locale_arguments=None)
...
+            case_type = CaseTypeXpath(USERCASE_TYPE).case()
+            case = UserCaseXPath(case_type).case()
```
Comment (snopoke) [inline corehq/apps/app_manager/suite_xml.py]: Pretty sure this should just be `case = UserCaseXPath(USERCASE_TYPE).case()`

**Comment by gcapalbo** [comment]
@kaapstorm Regarding the questions on CriticalSection -

General case and form processing uses some different locking mechanisms, and I'm not sure about the call center code as I haven't worked with it.  But basically if you ever notice situations where you're getting doc update conflicts or weird race condition issues, CriticalSection is a lightweight way to fix it.

The locking you implemented looks good - we need to use CriticalSection in enable_usercase in the off chance that it gets enabled simultaneously in two places (to prevent a doc update conflict on the domain).

Regarding your question on sync_user_case - if someone enables usercase and then right afterwards updates a user, it looks like the net effect is that sync_user_case will just be called twice for that user, right?  And since sync_user_case uses the CriticalSection, it will always make sure that the syncs happen serially and never simultaneously.  So I think it's good - the lock on enable_usercase makes sure that the domain doesn't have a doc update conflict, and the lock on sync_user_case makes sure that the sync process doesn't have a doc update conflict.

File: corehq/apps/app_manager/tasks.py [hunk 31]
```diff
@@ -0,0 +1,9 @@
+from celery.task import task
+from corehq.apps.users.models import CommCareUser
+
+
+@task
```
Comment (gcapalbo) [inline corehq/apps/app_manager/tasks.py]: Do you have a sense of what the priority is of this task?  By default this task will run on the main celery queue which is the high priority queue.  If you think this is a longer running / lower priority task then we could move it to the background_queue (see https://github.com/dimagi/commcare-hq/blob/9e7b34ca0cded7d8da8c89c1f081c7d5460741f6/corehq/apps/users/tasks.py#L31 for an example).

No need to block on this, just might be worth giving some thought.

File: corehq/apps/app_manager/util.py [hunk 32]
```diff
@@ -359,3 +380,31 @@ def get_commcare_versions(request_user):
...
+    return any(i.startswith(USERCASE_PREFIX) for i in items)
+
+
+def actions_use_usercase(actions):
+    return (any_usercase_items(actions['update_case']['update'].iterkeys()) or
+            any_usercase_items(actions['case_preload']['preload'].itervalues()))
+
+
+def enable_usercase(domain_name):
+    with CriticalSection([domain_name + '_enable_usercase']):
```
Comment (gcapalbo) [inline corehq/apps/app_manager/util.py]: No need to block on this, but I've been using the convention of 'keybase_%s' % identifier for the key names (i.e., key base first, then unique object identifier) to make it harder to have key name conflicts.

File: corehq/apps/app_manager/tasks.py (hunk 31 above)
Comment (snopoke) [inline corehq/apps/app_manager/tasks.py]: +1

File: corehq/apps/app_manager/suite_xml.py [hunk 33]
```diff
@@ -1490,6 +1496,34 @@ def get_auto_select_assertions(self, case_id_xpath, mode, locale_arguments=None)
...
+            if 'update_case' in actions and hasattr(actions['update_case'], 'update'):
+                return any_usercase_items(actions['update_case'].update.keys())
+            if 'case_preload' in actions:
+                return any_usercase_items(actions['case_preload'].preload.values())
+            return False
+
+        datums = []
+        if form.form_type == 'module_form' and uses_usercase(form):
+            if not self.is_usercase_enabled:
+                raise SuiteError('Form uses usercase, but usercase not enabled')
```
Comment (snopoke) [inline corehq/apps/app_manager/suite_xml.py]: Does this error appear to the user? If so should be translated.

File: corehq/apps/app_manager/util.py [hunk 34]
```diff
@@ -359,3 +381,31 @@ def get_commcare_versions(request_user):
...
+    return {k: v[n:] for k, v in items if v.startswith(USERCASE_PREFIX)}
+
+
+def any_usercase_items(items):
+    return any(i.startswith(USERCASE_PREFIX) for i in items)
+
+
+def actions_use_usercase(actions):
+    return (any_usercase_items(actions['update_case']['update'].iterkeys()) or
+            any_usercase_items(actions['case_preload']['preload'].itervalues()))
```
Comment (snopoke) [inline corehq/apps/app_manager/util.py]: could make this `action.get('update_case', {}).get('update', {}).iterkeys()` which would make it useful in the SuiteGenerator with `form.active_actions()`

File: corehq/apps/app_manager/const.py [hunk 35]
```diff
@@ -28,5 +28,8 @@
 ATTACHMENT_PREFIX = 'attachment:'
 
 CASE_ID = 'case_id'
+USERCASE_TYPE = 'commcare-user'
```
Comment (snopoke) [inline corehq/apps/app_manager/const.py]: Need to make sure user's can't create their own case type with this name.

File: corehq/apps/app_manager/xform.py [hunk 36]
```diff
@@ -976,6 +985,44 @@ def already_has_meta(self):
...
+    def _add_usercase_bind(self, usercase_path):
+        self.add_bind(
+            nodeset=usercase_path + 'case/@case_id',
+            calculate=SESSION_USERCASE_ID,
+        )
+
+    def add_usercase(self, form):
+        from corehq.apps.app_manager.util import split_path, get_usercase_keys, get_usercase_values
+
+        usercase_path = 'usercase/'
```
Comment (snopoke) [inline corehq/apps/app_manager/xform.py]: Maybe prefix with `commcare_`

File: corehq/apps/app_manager/xform.py [hunk 37]
```diff
@@ -1422,6 +1472,9 @@ def check_case_type(action):
             if action.preload:
                 self.add_casedb()
                 for nodeset, property in action.preload.items():
+                    if property.startswith(USERCASE_PREFIX):
+                        # Ignore usercase properties
+                        continue
```
Comment (snopoke) [inline corehq/apps/app_manager/xform.py]: Don't need this here for AdvancedForms

File: corehq/apps/app_manager/xform.py [hunk 38]
```diff
@@ -976,6 +985,44 @@ def already_has_meta(self):
...
+                property_xpath = {
+                    'name': 'case_name',
+                    'owner_id': '@owner_id'
+                }.get(property_, property_)
+
+                id_xpath = get_case_parent_id_xpath(parent_path, case_id_xpath=SESSION_USERCASE_ID)
+                self.add_setvalue(
+                    ref=nodeset,
+                    value=id_xpath.case().property(property_xpath),
+                )
```
Comment (snopoke) [inline corehq/apps/app_manager/xform.py]: Considering the similarity to normal preload block it should be easy to extract this to a function.

File: corehq/apps/smsforms/app.py [hunk 39]
```diff
@@ -56,9 +61,20 @@ def start_session(domain, contact, app, module, form, case_id=None, yield_respon
...
+            extra_datums = suite_gen.get_extra_case_id_datums(form)
+        except SuiteError:
+            _assert = soft_assert(['nhooper_at_dimagi_dot_com'.replace('_at_', '@').replace('_dot_', '.')])
+            _assert(False, 'form uses usercase, but app_manager did not enable usercase for the domain')
+        else:
+            datums.extend(extra_datums)
+            if contact.doc_type == 'CommCareUser' and suite_gen.any_usercase_datums(extra_datums):
+                usercase = get_case_by_domain_hq_user_id(domain, contact.get_id, include_docs=False)
+                if usercase:
+                    session_data[USERCASE_ID] = usercase['id']
```
Comment (snopoke) [inline corehq/apps/smsforms/app.py]: Probably worth extracting this to a util function `get_cloudcare_session_data`

File: corehq/apps/smsforms/app.py [hunk 40]
```diff
@@ -56,9 +61,20 @@ def start_session(domain, contact, app, module, form, case_id=None, yield_respon
...
+        suite_gen = SuiteGenerator(app, is_usercase_enabled(domain))
         datums = suite_gen.get_new_case_id_datums_meta(form)
         session_data.update({meta['datum'].id: uuid.uuid4().hex for meta in datums})
+        try:
+            extra_datums = suite_gen.get_extra_case_id_datums(form)
+        except SuiteError:
+            _assert = soft_assert(['nhooper_at_dimagi_dot_com'.replace('_at_', '@').replace('_dot_', '.')])
+            _assert(False, 'form uses usercase, but app_manager did not enable usercase for the domain')
+        else:
+            datums.extend(extra_datums)
```
Comment (snopoke) [inline corehq/apps/smsforms/app.py]: I don't think this is necessary since `datums` isn't used below.

File: corehq/apps/smsforms/app.py [hunk 41]
```diff
@@ -56,9 +61,20 @@ def start_session(domain, contact, app, module, form, case_id=None, yield_respon
         }
     
     if app and form:
```
Comment (gcapalbo) [inline corehq/apps/smsforms/app.py]: Before we merge this we should make sure that the tests in the following files pass (they must be run manually by uncommenting them from the corresponding tests/__init__.py file):

corehq.apps.sms.tests.inbound_handlers
corehq.apps.kookoo.tests.outbound

Instructions for how to setup the test environment are here: https://github.com/dimagi/commcare-hq/blob/6b864322d159cb0f0d498eea57d234eeea6abd15/corehq/apps/sms/tests/util.py#L43

Comment (snopoke) [inline corehq/apps/smsforms/app.py]: Thanks, good to know.

Comment (kaapstorm) [inline corehq/apps/smsforms/app.py]: kookoo tests pass. corehq.apps.sms.tests.inbound_handlers.KeywordTestCase.test_all_inbound fails at line 124 with "AssertionError: u'arm_a' != 'arm_b'" in both this branch and on master. Checking it out.

Comment (gcapalbo) [inline corehq/apps/smsforms/app.py]: @kaapstorm Sorry I should have mentioned sometimes the tests fail for some people because of something funny with couch where there needs to be a delay before querying for something after saving it. I ran all the manual sms and ivr tests and they passed, so no need to rerun it, but I'm guessing if you add sleep(1) (or some bigger number) in these places it would pass for you:

https://github.com/dimagi/commcare-hq/blob/9baeaa823a47063f958f30c380fa43ea3e0ad97a/corehq/apps/sms/tests/util.py#L240
https://github.com/dimagi/commcare-hq/blob/9baeaa823a47063f958f30c380fa43ea3e0ad97a/corehq/apps/sms/tests/util.py#L263

**Comment by czue** [comment]
@kaapstorm let me know if you want me to buddy-review this beast, though at this point I'm tempted to let @snopoke and @gcapalbo take it over the finish line.

**Comment by czue** [comment]
(although actually it's not quite as big as I thought so am open to reviewing if you think it'd be valuable)

**Comment by kaapstorm** [comment]
Thanks for the offer @czue. @snopoke and @gcapalbo have given excellent feedback. You're welcome to join, but I think it'll be OK for you to skip this one.

File: corehq/apps/smsforms/app.py (hunk 41 above)
Comment (kaapstorm) [inline corehq/apps/smsforms/app.py]: Thanks @gcapalbo, you're right. Adding sleep(1) fixed it. All passing now.

**Comment by snopoke** [comment]
Going to merge this now expecting that there are going to be some breaking changes in the next few days. e.g. changing `user:` to `user/`
